[workspace]
resolver = "2"
members = [
    "components/*",
]
exclude = [
    "components/wit",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wit-bindgen = { version = "0.60.0", git = "https://github.com/bytecodealliance/wit-bindgen.git", rev = "d92cfd3497a7adfbe70f03886c11def2deab6faa" }
