[workspace]
resolver = "2"
members = [
    "components/*",
    "crates/*",
]
exclude = [
    "components/gate",
    "components/latch-method-readonly",
    "components/latch-method-readonly-config",
    "components/wit",
]

[workspace.dependencies]
latch-n = { path = "./crates/latch-n" }
wit-bindgen = "0.61.0"
