//! Expanded for the `error-code` generated by wit-bindgen, as the components generate it.

mod bindings;

use bindings::wasi::http::types::{
    DnsErrorPayload, ErrorCode, FieldSizePayload, TlsAlertReceivedPayload,
};

fn name(error_code: ErrorCode) -> String {
    http_utils::format_http_error_code!(ErrorCode, &error_code).into_owned()
}

#[test]
fn names_without_a_payload() {
    assert_eq!(name(ErrorCode::HttpRequestDenied), "http-request-denied");
    assert_eq!(
        name(ErrorCode::DestinationIpProhibited),
        "destination-ip-prohibited"
    );
    assert_eq!(
        name(ErrorCode::HttpRequestUriTooLong),
        "http-request-uri-too-long"
    );
}

#[test]
fn optional_values() {
    assert_eq!(
        name(ErrorCode::HttpResponseBodySize(None)),
        "http-response-body-size"
    );
    assert_eq!(
        name(ErrorCode::HttpResponseBodySize(Some(1024))),
        "http-response-body-size<1024>"
    );
    assert_eq!(
        name(ErrorCode::HttpResponseContentCoding(Some("br".to_string()))),
        "http-response-content-coding<br>"
    );
    assert_eq!(name(ErrorCode::InternalError(None)), "internal-error");
    assert_eq!(
        name(ErrorCode::InternalError(Some("boom".to_string()))),
        "internal-error<boom>"
    );
}

#[test]
fn records_with_the_fields_that_have_a_value() {
    assert_eq!(
        name(ErrorCode::DnsError(DnsErrorPayload {
            rcode: Some("NXDOMAIN".to_string()),
            info_code: Some(3),
        })),
        "dns-error<rcode=NXDOMAIN,info-code=3>"
    );
    assert_eq!(
        name(ErrorCode::TlsAlertReceived(TlsAlertReceivedPayload {
            alert_id: Some(40),
            alert_message: None,
        })),
        "tls-alert-received<alert-id=40>"
    );
    assert_eq!(
        name(ErrorCode::HttpResponseHeaderSize(FieldSizePayload {
            field_name: Some("x-a".to_string()),
            field_size: Some(10),
        })),
        "http-response-header-size<field-name=x-a,field-size=10>"
    );
    // a record without any value is the name alone
    assert_eq!(
        name(ErrorCode::HttpRequestTrailerSize(FieldSizePayload {
            field_name: None,
            field_size: None,
        })),
        "http-request-trailer-size"
    );
    assert_eq!(
        name(ErrorCode::HttpRequestHeaderSize(None)),
        "http-request-header-size"
    );
}
