//! Expanded for the `method` generated by wit-bindgen, as the components generate it.

mod bindings;

use bindings::wasi::http::types;

fn method(method: types::Method) -> String {
    // a path to the type, as the gates use it
    http_utils::format_http_method!(types::Method, &method).into_owned()
}

#[test]
fn methods_in_lower_case() {
    assert_eq!(method(types::Method::Get), "get");
    assert_eq!(method(types::Method::Patch), "patch");
    assert_eq!(method(types::Method::Other("PURGE".to_string())), "purge");
}
