//! Expanded for the `error-code` generated by wit-bindgen, as the components generate it.

mod bindings;

use bindings::wasi::http::types::{self, ErrorCode};

/// Every variant of `error-code`, as written in the WIT, in lower case.
const NAMES: [&str; 39] = [
    "dns-timeout",
    "dns-error",
    "destination-not-found",
    "destination-unavailable",
    "destination-ip-prohibited",
    "destination-ip-unroutable",
    "connection-refused",
    "connection-terminated",
    "connection-timeout",
    "connection-read-timeout",
    "connection-write-timeout",
    "connection-limit-reached",
    "tls-protocol-error",
    "tls-certificate-error",
    "tls-alert-received",
    "http-request-denied",
    "http-request-length-required",
    "http-request-body-size",
    "http-request-method-invalid",
    "http-request-uri-invalid",
    "http-request-uri-too-long",
    "http-request-header-section-size",
    "http-request-header-size",
    "http-request-trailer-section-size",
    "http-request-trailer-size",
    "http-response-incomplete",
    "http-response-header-section-size",
    "http-response-header-size",
    "http-response-body-size",
    "http-response-trailer-section-size",
    "http-response-trailer-size",
    "http-response-transfer-coding",
    "http-response-content-coding",
    "http-response-timeout",
    "http-upgrade-failed",
    "http-protocol-error",
    "loop-detected",
    "configuration-error",
    "internal-error",
];

fn parse(name: &str) -> Option<ErrorCode> {
    http_utils::parse_http_error_code!(types, name)
}

#[test]
fn parses_every_name_formatted() {
    for name in NAMES {
        let error_code = parse(name).unwrap_or_else(|| panic!("{name} parses"));
        // an empty payload formats as the name alone
        assert_eq!(
            http_utils::format_http_error_code!(ErrorCode, &error_code),
            name
        );
    }
}

#[test]
fn not_an_error_code() {
    assert!(parse("").is_none());
    assert!(
        parse("HTTP-request-denied").is_none(),
        "names are lower case"
    );
    assert!(
        parse("http-request-denied<1>").is_none(),
        "payloads aren't parsed"
    );
}
