//! Expanded for the `scheme` generated by wit-bindgen, as the components generate it.

mod bindings;

use bindings::wasi::http::types;

fn scheme(scheme: types::Scheme) -> String {
    http_utils::format_http_scheme!(types::Scheme, &scheme).into_owned()
}

#[test]
fn schemes_in_lower_case() {
    assert_eq!(scheme(types::Scheme::Https), "https");
    assert_eq!(scheme(types::Scheme::Other("FTP".to_string())), "ftp");
}
