//! Bindings for the tests, generated by wit-bindgen from the repository's `imports` world, the same
//! generator and `wasi:http/types` the components use. A change to either is a change the tests
//! see.

wit_bindgen::generate!({
    path: "../../wit",
    world: "imports",
    generate_all,
});
