[package]
name = "trace-handler"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]
# shared with the other trace components
path = "../../crates/trace/src/lib.rs"

[features]
default = ["handler"]
client = []
handler = []

[dependencies]
http-utils = { workspace = true }
wit-bindgen = { workspace = true, features = ["async-spawn"] }

[dev-dependencies]
test-harness = { workspace = true }
tokio = { workspace = true }
wasmtime = { workspace = true }
